version: '2'

services:

  app_data:
    image: tianon/true
    volumes:
      - .:/var/node/app/

  react:
    image: node:6
    volumes_from:
      - app_data
    working_dir: /var/node/app/
    ports:
      - 3000:3000
    command: yarn start

  react_test:
    image: node:6
    volumes_from:
      - app_data
    working_dir: /var/node/app/
    command: yarn test

  cli:
    image: node:6
    volumes_from:
      - app_data
    working_dir: /var/node/app/
