version: '2'

services:

  app_data:
    image: tianon/true
    volumes:
      - .:/usr/src/app/

  react:
    build: .
    volumes_from:
      - app_data
    working_dir: /usr/src/app/
    ports:
      - 3000:3000

  react_test:
    build: .
    volumes_from:
      - app_data
    working_dir: /usr/src/app/
    command: yarn test

  cli:
    build: .
    volumes_from:
      - app_data
    working_dir: /usr/src/app/
